from core.utils import BaseEnum


class StateType(BaseEnum):
    STATE = 10
    UNION_TERITORY = 20


class StoreServics(BaseEnum):
    ALL = 10
    LAUNDRY = 20
    SELLING_WHOLESALE = 30
    SELLING_RETAIL = 40
    CUT_PIECE_CENTER = 70


class StoreSubService(BaseEnum):
    WASHING = 10
    IRON = 20
    DRY_CLEANING = 30
    STAIN_REMOVAL = 40
    FOLDING = 50
    DYEING = 60
    BLEACHING = 70
    BULK_ORDER_PROCESSING = 80
    CUSTOM_PACKAGING = 90
    WAREHOUSING = 100
    DISTRIBUTION = 110
    SHIPPING_LOGISTICS = 120
    CUSTOM_FITTING = 130
    GIFT_WRAPPING = 140
    HOME_DELIVERY = 150
    IN_STORE_PICKUP = 160
    PERSONAL_SHOPPER = 170
    WHOLESALE_LAUNDRY_PACKAGING = 180
    RETAIL_LAUNDRY_SERVICE = 190
    FABRIC_CUTTING = 200
    FABRIC_SORTING = 210
    CUSTOM_LABELING = 220


class HolidayType(BaseEnum):
    PUBLIC_HOLIDAY = 10
    STORE_HOLIDAY = 20
