name: Ruff Linter and Formatter

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.7"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff Lint
      id: ruff
      run: |
        ruff check . --fix --unsafe-fixes --force-exclude

    - name: Run Ruff Format
      id: ruff-format
      run: |
        ruff format --force-exclude
